on:
  workflow_dispatch:

name: Deploy to Test Website

jobs:
  deploy: 
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.RAIDBOXES_PRIVATE_KEY }}
          SOURCE: "/"
          REMOTE_HOST: ${{ secrets.RAIDBOXES_REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.RAIDBOXES_REMOTE_USER }}
          REMOTE_PORT: ${{ secrets.RAIDBOXES_REMOTE_PORT }}
          TARGET: ${{ secrets.RAIDBOXES_REMOTE_TARGET }}/wp-content/plugins/fvw-easy-init
          EXCLUDE: ".github, .git, .gitignore, release.sh, README.md"